### ISSUE TITLE
Define the Dependency managemt we are going to use on our project.

### ISSUE THREAD

**Issue by pedrocecchetti** [pedrocecchetti/ikita#3]
On this matter I have mentione in #2 that we are supposed to have on our root repository the dependency management files(pyproject.toml + *.lock). For that we could use many different tools. 

I was reading this [article](https://alpopkes.com/posts/python/packaging_tools/) and really wanted to try [rye](https://github.com/astral-sh/rye), as it seems  very complete and would be the only solution we would use for our project. 

Regarding the code formatting and linting, I was thinking we could use [ruff](https://github.com/astral-sh/ruff) as I have been using it and really think it makes easier to standardize code and make sure the formatting is consistent as well. 

I would like your opinion on the matters @brunachaves :)

**Comment by pedrocecchetti** [comment]
Added a PR on it for us to discuss it

**Comment by brunachaves** [comment]
Done on #5
